In [1]:
import pandas as pd
dados = pd.read_csv('coaster_db.csv')

In [2]:
dados

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,...,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,600 ft (180 m),6 mph (9.7 km/h),Coney Island,Removed,"June 16, 1884",Wood,LaMarcus Adna Thompson,NaN,Lift Packed,...,6 mph,9.7 km/h,6.0,mph,6.0,50.0,ft,NaN,0,2.9
1,Flip Flap Railway,NaN,NaN,Sea Lion Park,Removed,1895,Wood,Lina Beecher,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,American Dreier Looping,"3,444 ft (1,050 m)",53 mph (85 km/h),Other,NaN,NaN,Steel,Anton Schwarzkopf,55 in (140 cm),NaN,...,53 mph,85 km/h,53.0,mph,53.0,111.0,ft,NaN,3,4.7
1083,Pantheon (roller coaster),"3,328 ft (1,014 m)",73 mph (117 km/h),Busch Gardens Williamsburg,Under construction,2022,Steel – Launched,Intamin,NaN,Blitz Coaster,...,73 mph,117 km/h,73.0,mph,73.0,178.0,ft,NaN,2,NaN
1084,Tron Lightcycle Power Run,"3,169.3 ft (966.0 m)",59.3[1] mph (95.4 km/h),Other,NaN,"June 16, 2016",Steel – Launched,Vekoma,4[2] ft (122 cm),Motorbike roller coaster,...,59.3 mph,95.4 km/h,59.3,mph,59.3,78.1,ft,NaN,0,4.0
1085,Tumbili,770 ft (230 m),34 mph (55 km/h),Kings Dominion,Under construction,NaN,Steel – 4th Dimension – Wing Coaster,S&S – Sansei Technologies,NaN,4D Free Spin,...,34 mph,55 km/h,34.0,mph,34.0,112.0,ft,NaN,0,NaN
1086,Wonder Woman Flight of Courage,"3,300 ft (1,000 m)",58 mph (93 km/h),Six Flags Magic Mountain,Under construction,2022,Steel – Single-rail,Rocky Mountain Construction,NaN,Raptor – Custom,...,58 mph,93 km/h,58.0,mph,58.0,131.0,ft,NaN,3,NaN

In [6]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1087 entries, 0 to 1086
Data columns (total 56 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   coaster_name                   1087 non-null   object
 1   Length                         953 non-null    object
 2   Speed                          937 non-null    object
 3   Location                       1087 non-null   object
 4   Status                         874 non-null    object
 5   Opening date                   837 non-null    object
 6   Type                           1087 non-null   object
 7   Manufacturer                   1028 non-null   object
 8   Height restriction             831 non-null    object
 9   Model                          744 non-null    object
 10  Height                         965 non-null    object
 11  Inversions                     932 non-null    float64
 12  Lift/launch system             795 non-null    object
 13  Cost                           382 non-null    object
 14  Trains                         718 non-null    object
 15  Park section                   487 non-null    object
 16  Duration                       765 non-null    object
 17  Capacity                       575 non-null    object
 18  G-force                        362 non-null    object
 19  Designer                       578 non-null    object
 20  Max vertical angle             357 non-null    object
 21  Drop                           494 non-null    object
 22  Soft opening date              96 non-null     object
 23  Fast Lane available            69 non-null     object
 24  Replaced                       173 non-null    object
 25  Track layout                   335 non-null    object
 26  Fastrack available             19 non-null     object
 27  Soft opening date.1            96 non-null     object
 28  Closing date                   236 non-null    object
 29  Opened                         27 non-null     object
 30  Replaced by                    88 non-null     object
 31  Website                        87 non-null     object
 32  Flash Pass Available           50 non-null     object
 33  Must transfer from wheelchair  106 non-null    object
 34  Theme                          44 non-null     object
 35  Single rider line available    81 non-null     object
 36  Restraint Style                22 non-null     object
 37  Flash Pass available           46 non-null     object
 38  Acceleration                   60 non-null     object
 39  Restraints                     24 non-null     object
 40  Name                           35 non-null     object
 41  year_introduced                1087 non-null   int64
 42  latitude                       812 non-null    float64
 43  longitude                      812 non-null    float64
 44  Type_Main                      1087 non-null   object
 45  opening_date_clean             837 non-null    object
 46  speed1                         937 non-null    object
 47  speed2                         935 non-null    object
 48  speed1_value                   937 non-null    float64
 49  speed1_unit                    937 non-null    object
 50  speed_mph                      937 non-null    float64
 51  height_value                   965 non-null    float64
 52  height_unit                    965 non-null    object
 53  height_ft                      171 non-null    float64
 54  Inversions_clean               1087 non-null   int64
 55  Gforce_clean                   362 non-null    float64
dtypes: float64(8), int64(2), object(46)
memory usage: 475.7+ KB

In [7]:
dados.describe()

,Inversions,year_introduced,latitude,longitude,speed1_value,speed_mph,height_value,height_ft,Inversions_clean,Gforce_clean
count,932.000000,1087.000000,812.000000,812.000000,937.000000,937.000000,965.000000,171.000000,1087.000000,362.000000
mean,1.547210,1994.986201,38.373484,-41.595373,53.850374,48.617289,89.575171,101.996491,1.326587,3.824006
std,2.114073,23.475248,15.516596,72.285227,23.385518,16.678031,136.246444,67.329092,2.030854,0.989998
min,0.000000,1884.000000,-48.261700,-123.035700,5.000000,5.000000,4.000000,13.100000,0.000000,0.800000
25%,0.000000,1989.000000,35.031050,-84.552200,40.000000,37.300000,44.000000,51.800000,0.000000,3.400000
50%,0.000000,2000.000000,40.289800,-76.653600,50.000000,49.700000,79.000000,91.200000,0.000000,4.000000
75%,3.000000,2010.000000,44.799600,2.778100,63.000000,58.000000,113.000000,131.200000,2.000000,4.500000
max,14.000000,2022.000000,63.230900,153.426500,240.000000,149.100000,3937.000000,377.300000,14.000000,12.000000

In [8]:
dados.head()

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,...,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,600 ft (180 m),6 mph (9.7 km/h),Coney Island,Removed,"June 16, 1884",Wood,LaMarcus Adna Thompson,NaN,Lift Packed,...,6 mph,9.7 km/h,6.0,mph,6.0,50.0,ft,NaN,0,2.9
1,Flip Flap Railway,NaN,NaN,Sea Lion Park,Removed,1895,Wood,Lina Beecher,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN

In [9]:
dados.tail()

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,...,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
1082,American Dreier Looping,"3,444 ft (1,050 m)",53 mph (85 km/h),Other,NaN,NaN,Steel,Anton Schwarzkopf,55 in (140 cm),NaN,...,53 mph,85 km/h,53.0,mph,53.0,111.0,ft,NaN,3,4.7
1083,Pantheon (roller coaster),"3,328 ft (1,014 m)",73 mph (117 km/h),Busch Gardens Williamsburg,Under construction,2022,Steel – Launched,Intamin,NaN,Blitz Coaster,...,73 mph,117 km/h,73.0,mph,73.0,178.0,ft,NaN,2,NaN
1084,Tron Lightcycle Power Run,"3,169.3 ft (966.0 m)",59.3[1] mph (95.4 km/h),Other,NaN,"June 16, 2016",Steel – Launched,Vekoma,4[2] ft (122 cm),Motorbike roller coaster,...,59.3 mph,95.4 km/h,59.3,mph,59.3,78.1,ft,NaN,0,4.0
1085,Tumbili,770 ft (230 m),34 mph (55 km/h),Kings Dominion,Under construction,NaN,Steel – 4th Dimension – Wing Coaster,S&S – Sansei Technologies,NaN,4D Free Spin,...,34 mph,55 km/h,34.0,mph,34.0,112.0,ft,NaN,0,NaN
1086,Wonder Woman Flight of Courage,"3,300 ft (1,000 m)",58 mph (93 km/h),Six Flags Magic Mountain,Under construction,2022,Steel – Single-rail,Rocky Mountain Construction,NaN,Raptor – Custom,...,58 mph,93 km/h,58.0,mph,58.0,131.0,ft,NaN,3,NaN

In [11]:
dados.shape

(1087, 56)

In [13]:
dados.columns

Index(['coaster_name', 'Length', 'Speed', 'Location', 'Status', 'Opening date',
       'Type', 'Manufacturer', 'Height restriction', 'Model', 'Height',
       'Inversions', 'Lift/launch system', 'Cost', 'Trains', 'Park section',
       'Duration', 'Capacity', 'G-force', 'Designer', 'Max vertical angle',
       'Drop', 'Soft opening date', 'Fast Lane available', 'Replaced',
       'Track layout', 'Fastrack available', 'Soft opening date.1',
       'Closing date', 'Opened', 'Replaced by', 'Website',
       'Flash Pass Available', 'Must transfer from wheelchair', 'Theme',
       'Single rider line available', 'Restraint Style',
       'Flash Pass available', 'Acceleration', 'Restraints', 'Name',
       'year_introduced', 'latitude', 'longitude', 'Type_Main',
       'opening_date_clean', 'speed1', 'speed2', 'speed1_value', 'speed1_unit',
       'speed_mph', 'height_value', 'height_unit', 'height_ft',
       'Inversions_clean', 'Gforce_clean'],
      dtype='object')

In [14]:
dados.Location.value_counts()

Location
Other                                 250
Cedar Point                            19
Kings Island                           19
Six Flags Magic Mountain               17
Hersheypark                            16
                                     ...
New York-New York Hotel and Casino      1
Granada Studios Tour                    1
Funtown Splashtown USA                  1
Suzuka, Mie Prefecture, Japan           1
Epcot                                   1
Name: count, Length: 280, dtype: int64

In [15]:
dados.Type.value_counts()

Type
Steel                            308
Wood                             164
Other                             72
Steel – Launched                  63
Steel – Inverted                  60
                                ...
Wood – Shuttle                     1
Steel junior roller coaster        1
Steel – Euro-Fighter – Indoor      1
Steel – Twister                    1
Steel – Family – Wild Mouse        1
Name: count, Length: 98, dtype: int64

In [17]:
dados['Restraint Style'].value_counts()

Restraint Style
Over-the-shoulder                                                      17
Lap Bar                                                                 1
Individual ratcheting lap bar, formerly individual shoulder harness     1
Seat Belt / Lap Bar                                                     1
Over the Shoulder Restraints                                            1
Lapbars with seatbelt and shinguards                                    1
Name: count, dtype: int64

In [18]:
dados.sample(5)

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,...,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
867,Goliath (Six Flags New England),"1,204.1 ft (367.0 m)",65.6 mph (105.6 km/h),Other,NaN,NaN,Steel – Shuttle – Inverted,Vekoma,54–75 in (137–191 cm),Giant Inverted Boomerang,...,65.6 mph,105.6 km/h,65.6,mph,65.6,191.6,ft,NaN,3,4.5
822,Sky Rocket,"2,100 ft (640 m)",50 mph (80 km/h),Kennywood Park,Operating,"June 29, 2010",Steel,Premier Rides,52 in (132 cm),NaN,...,50 mph,80 km/h,50.0,mph,50.0,95.0,ft,NaN,3,0.8
757,Dragon's Run,"3,738 ft (1,139 m)",65 mph (105 km/h),Other,NaN,NaN,Steel,Bolliger & Mabillard,54 in (137 cm),Sitting Coaster,...,65 mph,105 km/h,65.0,mph,65.0,155.0,ft,NaN,6,NaN
695,Wild Mouse (Beech Bend Park),"1,377.9 ft (420.0 m)",29.1 mph (46.8 km/h),Beech Bend Park,Operating,2005,Steel – Wild Mouse,Zamperla,42 in (107 cm),Twister Coaster 420STD,...,29.1 mph,46.8 km/h,29.1,mph,29.1,42.7,ft,NaN,0,2.5
1030,Hagrid's Magical Creatures Motorbike Adventure,"5,053 ft (1,540 m)",50 mph (80 km/h),Universal's Islands of Adventure,Operating,"June 13, 2019[1]",Steel – Launched,Intamin,48 in (122 cm),Motorbike roller coaster,...,50 mph,80 km/h,50.0,mph,50.0,65.0,ft,NaN,0,NaN

In [19]:
dados.sample(frac = 0.1)

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,...,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
854,Van Helsing's Factory,"400 m (1,300 ft)",36 km/h (22 mph),Movie Park Germany,Operating,18 June 2011,Steel – Enclosed,Gerstlauer,120 cm (3 ft 11 in),Bobsled Coaster,...,36 km/h,22 mph,36.0,km/h,22.4,8.0,m,26.2,0,4.0
855,Vipère (roller coaster),825 ft (251 m),37 mph (60 km/h),Other,NaN,"July 1, 2011",Steel – 4th Dimension,Intamin,52–77 in (132–196 cm),Ball Coaster – ZacSpin,...,37 mph,60 km/h,37.0,mph,37.0,107.0,ft,NaN,0,NaN
968,Lost Gravity (roller coaster),"680 m (2,230 ft)",87 km/h (54 mph),Walibi Holland,Operating,24 March 2016,Steel,Mack Rides,140 cm (4 ft 7 in),BigDipper,...,87 km/h,54 mph,87.0,km/h,54.1,32.0,m,105.0,2,4.3
856,Wood Coaster (Mountain Flyer),"4,817 ft (1,468 m)",61.2 mph (98.5 km/h),OCT East,Operating,"July 19, 2011",Wood – Terrain,Great Coasters International,NaN,NaN,...,61.2 mph,98.5 km/h,61.2,mph,61.2,147.0,ft,NaN,0,NaN
444,Journey to Atlantis,NaN,NaN,SeaWorld Orlando,Operating,"April 17, 1998",Steel,Mack Rides,42 in (107 cm),Water Coaster,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,Mystery Mine,"1,804.5 ft (550.0 m)",43.5 mph (70.0 km/h),Dollywood,Operating,"April 13, 2007",Steel – Euro-Fighter,Gerstlauer,48–76 in (122–193 cm),Euro-Fighter (Custom),...,43.5 mph,70.0 km/h,43.5,mph,43.5,85.3,ft,NaN,2,NaN
615,Superman: Ultimate Flight,"2,759–2,798 ft (841–853 m)",51 mph (82 km/h),Other,NaN,NaN,Steel – Flying,Bolliger & Mabillard,54 in (137 cm),Flying Coaster - Superman,...,51 mph,82 km/h,51.0,mph,51.0,106.0,ft,NaN,2,3.0
742,Rage (roller coaster),"1,184 ft (361 m)",43.5 mph (70.0 km/h),Adventure Island,Operating,10 February 2007,Steel – Euro-Fighter,Gerstlauer,NaN,Euro-Fighter Model 320+,...,43.5 mph,70.0 km/h,43.5,mph,43.5,72.0,ft,NaN,3,4.5
48,Zip (roller coaster),"2,500 ft (760 m)",NaN,Oaks Amusement Park,Removed,1927,Wood,Traver Engineering,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,60.0,ft,NaN,0,NaN
553,Steel Dragon 2000,"2,479 m (8,133 ft)",152.9 km/h (95.0 mph),Nagashima Spa Land,Operating,1 August 2000,Steel,D. H. Morgan Manufacturing,140–185 cm (4 ft 7 in–6 ft 1 in),NaN,...,152.9 km/h,95.0 mph,152.9,km/h,95.0,97.0,m,318.2,0,NaN

In [20]:
dados.shape

(1087, 56)

In [21]:
dados.speed_mph.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1087 entries, 0 to 1086
Series name: speed_mph
Non-Null Count  Dtype
--------------  -----
937 non-null    float64
dtypes: float64(1)
memory usage: 8.6 KB

In [22]:
dados.speed_mph.describe()

count    937.000000
mean      48.617289
std       16.678031
min        5.000000
25%       37.300000
50%       49.700000
75%       58.000000
max      149.100000
Name: speed_mph, dtype: float64

In [23]:
149*1.6

238.4

In [26]:
total_nulos_speed_mph = dados.speed_mph.isnull().sum()

In [27]:
total_linhas = dados.shape[0]

In [28]:
pc_nulos_speed_mph = total_nulos_speed_mph/total_linhas*100
print(f'O total de nulos na coluna "speed_mph" representa {pc_nulos_speed_mph} do total de registros')

O total de nulos na coluna "speed_mph" representa 13.799448022079117 do total de registros

In [29]:
total_linhas = dados.shape[0]
for coluna in dados.columns:
    total_nulos_coluna = dados[coluna].isnull().sum()
    pc_nulos_coluna = round(total_nulos_coluna/total_linhas*100,2)
    print(f'A coluna "{coluna}" apresenta {total_nulos_coluna} registros nulos, que representam {pc_nulos_coluna} % do total de registros')

A coluna "coaster_name" apresenta 0 registros nulos, que representam 0.0 % do total de registros
A coluna "Length" apresenta 134 registros nulos, que representam 12.33 % do total de registros
A coluna "Speed" apresenta 150 registros nulos, que representam 13.8 % do total de registros
A coluna "Location" apresenta 0 registros nulos, que representam 0.0 % do total de registros
A coluna "Status" apresenta 213 registros nulos, que representam 19.6 % do total de registros
A coluna "Opening date" apresenta 250 registros nulos, que representam 23.0 % do total de registros
A coluna "Type" apresenta 0 registros nulos, que representam 0.0 % do total de registros
A coluna "Manufacturer" apresenta 59 registros nulos, que representam 5.43 % do total de registros
A coluna "Height restriction" apresenta 256 registros nulos, que representam 23.55 % do total de registros
A coluna "Model" apresenta 343 registros nulos, que representam 31.55 % do total de registros
A coluna "Height" apresenta 122 registros nulos, que representam 11.22 % do total de registros
A coluna "Inversions" apresenta 155 registros nulos, que representam 14.26 % do total de registros
A coluna "Lift/launch system" apresenta 292 registros nulos, que representam 26.86 % do total de registros
A coluna "Cost" apresenta 705 registros nulos, que representam 64.86 % do total de registros
A coluna "Trains" apresenta 369 registros nulos, que representam 33.95 % do total de registros
A coluna "Park section" apresenta 600 registros nulos, que representam 55.2 % do total de registros
A coluna "Duration" apresenta 322 registros nulos, que representam 29.62 % do total de registros
A coluna "Capacity" apresenta 512 registros nulos, que representam 47.1 % do total de registros
A coluna "G-force" apresenta 725 registros nulos, que representam 66.7 % do total de registros
A coluna "Designer" apresenta 509 registros nulos, que representam 46.83 % do total de registros
A coluna "Max vertical angle" apresenta 730 registros nulos, que representam 67.16 % do total de registros
A coluna "Drop" apresenta 593 registros nulos, que representam 54.55 % do total de registros
A coluna "Soft opening date" apresenta 991 registros nulos, que representam 91.17 % do total de registros
A coluna "Fast Lane available" apresenta 1018 registros nulos, que representam 93.65 % do total de registros
A coluna "Replaced" apresenta 914 registros nulos, que representam 84.08 % do total de registros
A coluna "Track layout" apresenta 752 registros nulos, que representam 69.18 % do total de registros
A coluna "Fastrack available" apresenta 1068 registros nulos, que representam 98.25 % do total de registros
A coluna "Soft opening date.1" apresenta 991 registros nulos, que representam 91.17 % do total de registros
A coluna "Closing date" apresenta 851 registros nulos, que representam 78.29 % do total de registros
A coluna "Opened" apresenta 1060 registros nulos, que representam 97.52 % do total de registros
A coluna "Replaced by" apresenta 999 registros nulos, que representam 91.9 % do total de registros
A coluna "Website" apresenta 1000 registros nulos, que representam 92.0 % do total de registros
A coluna "Flash Pass Available" apresenta 1037 registros nulos, que representam 95.4 % do total de registros
A coluna "Must transfer from wheelchair" apresenta 981 registros nulos, que representam 90.25 % do total de registros
A coluna "Theme" apresenta 1043 registros nulos, que representam 95.95 % do total de registros
A coluna "Single rider line available" apresenta 1006 registros nulos, que representam 92.55 % do total de registros
A coluna "Restraint Style" apresenta 1065 registros nulos, que representam 97.98 % do total de registros
A coluna "Flash Pass available" apresenta 1041 registros nulos, que representam 95.77 % do total de registros
A coluna "Acceleration" apresenta 1027 registros nulos, que representam 94.48 % do total de registros
A coluna "Restraints" apresenta 1063 registros nulos, que representam 97.79 % do total de registros
A coluna "Name" apresenta 1052 registros nulos, que representam 96.78 % do total de registros
A coluna "year_introduced" apresenta 0 registros nulos, que representam 0.0 % do total de registros
A coluna "latitude" apresenta 275 registros nulos, que representam 25.3 % do total de registros
A coluna "longitude" apresenta 275 registros nulos, que representam 25.3 % do total de registros
A coluna "Type_Main" apresenta 0 registros nulos, que representam 0.0 % do total de registros
A coluna "opening_date_clean" apresenta 250 registros nulos, que representam 23.0 % do total de registros
A coluna "speed1" apresenta 150 registros nulos, que representam 13.8 % do total de registros
A coluna "speed2" apresenta 152 registros nulos, que representam 13.98 % do total de registros
A coluna "speed1_value" apresenta 150 registros nulos, que representam 13.8 % do total de registros
A coluna "speed1_unit" apresenta 150 registros nulos, que representam 13.8 % do total de registros
A coluna "speed_mph" apresenta 150 registros nulos, que representam 13.8 % do total de registros
A coluna "height_value" apresenta 122 registros nulos, que representam 11.22 % do total de registros
A coluna "height_unit" apresenta 122 registros nulos, que representam 11.22 % do total de registros
A coluna "height_ft" apresenta 916 registros nulos, que representam 84.27 % do total de registros
A coluna "Inversions_clean" apresenta 0 registros nulos, que representam 0.0 % do total de registros
A coluna "Gforce_clean" apresenta 725 registros nulos, que representam 66.7 % do total de registros

In [30]:
total_linhas = dados.shape[0]
coluna_nome = list()
total_nulo = list()
pc_total_nulo = list()
for coluna in dados.columns:
    coluna_nome.append(coluna)
    total_nulos_coluna = dados[coluna].isnull().sum()
    total_nulo.append(total_nulos_coluna)
    pc_nulos_coluna = round(total_nulos_coluna/total_linhas*100,2)
    pc_total_nulo.append(pc_nulos_coluna)

In [31]:
resumo = pd.DataFrame()
resumo['Nome da coluna'] = coluna_nome
resumo['Total nulos'] = total_nulo
resumo['Total nulos (pc)'] = pc_total_nulo

In [32]:
resumo

                   Nome da coluna  Total nulos  Total nulos (pc)
0                    coaster_name            0              0.00
1                          Length          134             12.33
2                           Speed          150             13.80
3                        Location            0              0.00
4                          Status          213             19.60
5                    Opening date          250             23.00
6                            Type            0              0.00
7                    Manufacturer           59              5.43
8              Height restriction          256             23.55
9                           Model          343             31.55
10                         Height          122             11.22
11                     Inversions          155             14.26
12             Lift/launch system          292             26.86
13                           Cost          705             64.86
14                         Trains          369             33.95
15                   Park section          600             55.20
16                       Duration          322             29.62
17                       Capacity          512             47.10
18                        G-force          725             66.70
19                       Designer          509             46.83
20             Max vertical angle          730             67.16
21                           Drop          593             54.55
22              Soft opening date          991             91.17
23            Fast Lane available         1018             93.65
24                       Replaced          914             84.08
25                   Track layout          752             69.18
26             Fastrack available         1068             98.25
27            Soft opening date.1          991             91.17
28                   Closing date          851             78.29
29                         Opened         1060             97.52
30                    Replaced by          999             91.90
31                        Website         1000             92.00
32           Flash Pass Available         1037             95.40
33  Must transfer from wheelchair          981             90.25
34                          Theme         1043             95.95
35    Single rider line available         1006             92.55
36                Restraint Style         1065             97.98
37           Flash Pass available         1041             95.77
38                   Acceleration         1027             94.48
39                     Restraints         1063             97.79
40                           Name         1052             96.78
41                year_introduced            0              0.00
42                       latitude          275             25.30
43                      longitude          275             25.30
44                      Type_Main            0              0.00
45             opening_date_clean          250             23.00
46                         speed1          150             13.80
47                         speed2          152             13.98
48                   speed1_value          150             13.80
49                    speed1_unit          150             13.80
50                      speed_mph          150             13.80
51                   height_value          122             11.22
52                    height_unit          122             11.22
53                      height_ft          916             84.27
54               Inversions_clean            0              0.00
55                   Gforce_clean          725             66.70

In [33]:
resumo = resumo.sort_values(by='Total nulos (pc)')

In [34]:
resumo

                   Nome da coluna  Total nulos  Total nulos (pc)
0                    coaster_name            0              0.00
44                      Type_Main            0              0.00
54               Inversions_clean            0              0.00
6                            Type            0              0.00
41                year_introduced            0              0.00
3                        Location            0              0.00
7                    Manufacturer           59              5.43
52                    height_unit          122             11.22
10                         Height          122             11.22
51                   height_value          122             11.22
1                          Length          134             12.33
2                           Speed          150             13.80
46                         speed1          150             13.80
48                   speed1_value          150             13.80
49                    speed1_unit          150             13.80
50                      speed_mph          150             13.80
47                         speed2          152             13.98
11                     Inversions          155             14.26
4                          Status          213             19.60
45             opening_date_clean          250             23.00
5                    Opening date          250             23.00
8              Height restriction          256             23.55
42                       latitude          275             25.30
43                      longitude          275             25.30
12             Lift/launch system          292             26.86
16                       Duration          322             29.62
9                           Model          343             31.55
14                         Trains          369             33.95
19                       Designer          509             46.83
17                       Capacity          512             47.10
21                           Drop          593             54.55
15                   Park section          600             55.20
13                           Cost          705             64.86
55                   Gforce_clean          725             66.70
18                        G-force          725             66.70
20             Max vertical angle          730             67.16
25                   Track layout          752             69.18
28                   Closing date          851             78.29
24                       Replaced          914             84.08
53                      height_ft          916             84.27
33  Must transfer from wheelchair          981             90.25
27            Soft opening date.1          991             91.17
22              Soft opening date          991             91.17
30                    Replaced by          999             91.90
31                        Website         1000             92.00
35    Single rider line available         1006             92.55
23            Fast Lane available         1018             93.65
38                   Acceleration         1027             94.48
32           Flash Pass Available         1037             95.40
37           Flash Pass available         1041             95.77
34                          Theme         1043             95.95
40                           Name         1052             96.78
29                         Opened         1060             97.52
39                     Restraints         1063             97.79
36                Restraint Style         1065             97.98
26             Fastrack available         1068             98.25

In [35]:
resumo = resumo.sort_values(by='Total nulos (pc)',ascending=False)
resumo

                   Nome da coluna  Total nulos  Total nulos (pc)
26             Fastrack available         1068             98.25
36                Restraint Style         1065             97.98
39                     Restraints         1063             97.79
29                         Opened         1060             97.52
40                           Name         1052             96.78
34                          Theme         1043             95.95
37           Flash Pass available         1041             95.77
32           Flash Pass Available         1037             95.40
38                   Acceleration         1027             94.48
23            Fast Lane available         1018             93.65
35    Single rider line available         1006             92.55
31                        Website         1000             92.00
30                    Replaced by          999             91.90
22              Soft opening date          991             91.17
27            Soft opening date.1          991             91.17
33  Must transfer from wheelchair          981             90.25
53                      height_ft          916             84.27
24                       Replaced          914             84.08
28                   Closing date          851             78.29
25                   Track layout          752             69.18
20             Max vertical angle          730             67.16
18                        G-force          725             66.70
55                   Gforce_clean          725             66.70
13                           Cost          705             64.86
15                   Park section          600             55.20
21                           Drop          593             54.55
17                       Capacity          512             47.10
19                       Designer          509             46.83
14                         Trains          369             33.95
9                           Model          343             31.55
16                       Duration          322             29.62
12             Lift/launch system          292             26.86
43                      longitude          275             25.30
42                       latitude          275             25.30
8              Height restriction          256             23.55
5                    Opening date          250             23.00
45             opening_date_clean          250             23.00
4                          Status          213             19.60
11                     Inversions          155             14.26
47                         speed2          152             13.98
48                   speed1_value          150             13.80
2                           Speed          150             13.80
46                         speed1          150             13.80
49                    speed1_unit          150             13.80
50                      speed_mph          150             13.80
1                          Length          134             12.33
51                   height_value          122             11.22
10                         Height          122             11.22
52                    height_unit          122             11.22
7                    Manufacturer           59              5.43
6                            Type            0              0.00
54               Inversions_clean            0              0.00
44                      Type_Main            0              0.00
41                year_introduced            0              0.00
3                        Location            0              0.00
0                    coaster_name            0              0.00

In [37]:
resumo = resumo.sort_values(by='Total nulos (pc)',ascending=False).reset_index(drop=True)
resumo

                   Nome da coluna  Total nulos  Total nulos (pc)
0              Fastrack available         1068             98.25
1                 Restraint Style         1065             97.98
2                      Restraints         1063             97.79
3                          Opened         1060             97.52
4                            Name         1052             96.78
5                           Theme         1043             95.95
6            Flash Pass available         1041             95.77
7            Flash Pass Available         1037             95.40
8                    Acceleration         1027             94.48
9             Fast Lane available         1018             93.65
10    Single rider line available         1006             92.55
11                        Website         1000             92.00
12                    Replaced by          999             91.90
13              Soft opening date          991             91.17
14            Soft opening date.1          991             91.17
15  Must transfer from wheelchair          981             90.25
16                      height_ft          916             84.27
17                       Replaced          914             84.08
18                   Closing date          851             78.29
19                   Track layout          752             69.18
20             Max vertical angle          730             67.16
21                        G-force          725             66.70
22                   Gforce_clean          725             66.70
23                           Cost          705             64.86
24                   Park section          600             55.20
25                           Drop          593             54.55
26                       Capacity          512             47.10
27                       Designer          509             46.83
28                         Trains          369             33.95
29                          Model          343             31.55
30                       Duration          322             29.62
31             Lift/launch system          292             26.86
32                      longitude          275             25.30
33                       latitude          275             25.30
34             Height restriction          256             23.55
35                   Opening date          250             23.00
36             opening_date_clean          250             23.00
37                         Status          213             19.60
38                     Inversions          155             14.26
39                         speed2          152             13.98
40                   speed1_value          150             13.80
41                          Speed          150             13.80
42                         speed1          150             13.80
43                    speed1_unit          150             13.80
44                      speed_mph          150             13.80
45                         Length          134             12.33
46                   height_value          122             11.22
47                         Height          122             11.22
48                    height_unit          122             11.22
49                   Manufacturer           59              5.43
50                           Type            0              0.00
51               Inversions_clean            0              0.00
52                      Type_Main            0              0.00
53                year_introduced            0              0.00
54                       Location            0              0.00
55                   coaster_name            0              0.00